---
title: "exercise1"
author: "Giulia Bertoldo"
date: "4/4/2022"
output: pdf_document
---
```{r}
# Load packages
library(metafor)


# (1) Create dataframe
study <- c('Goldham', 'Graham', 'Madison', 'Manning', 'Moyer')
t_died <- c(8, 12, 8, 80, 20)
t_total <- c(100, 100, 100, 1000, 250)
c_died <- c(14, 16, 12, 200, 24)
c_total <- c(100, 100, 100, 1000, 250)

df1 <- data.frame(study, t_died, t_total, c_died, c_total)
df1

```

\newpage
```{r}
# (1a) Inverse-variance weighted meta-analysis on the log odds ratio (FEM)
## Calculate log-odds ratio and sampling variance
df2 <- escalc(ai=t_died, ci=c_died, n1i=t_total, n2i=c_total,
              measure = 'OR',
              data=df1,
              append=TRUE)
df2

## FEM
## Weighted estimation (with inverse-variance weights) is used by default
FEM <- rma(yi=yi, vi=vi, data=df2, method="FE")
summary(FEM)

# (1b) What would you conclude about the mean effect size?
## The mean log-odds is about -0.82 meaning that the log-odds of
## dying in treatment condition are lower than in the control
## The result is statistically significant

# (1c) Is there evidence for study heterogeneity?
## The Q statistics is not significant at 5% alpha level (p=.07)
## so we cannot reject the null hypothesis of homogeneity
## However, Q-statistics and stat. power:
## we cannot conclude that there is actually homogeneity.

```

\newpage

```{r}
# (1d) Remove Manning study

df3 <-df2[-4,]
FEM3 <- rma(yi=df3$yi, vi=df3$vi, data=df3, method="FE")
summary(FEM3)
summary(FEM)

## I^2 moves from ~ 55% to 0%
## Test for homogeneity moves from p-value of 0.07 to 0.89
## Mean-estimate moves from -0.82 to -0.35: substantial decrease
## Mean-estimate is not significant anymore
## Indeed standard error is larger and the effect is not significant
## at 5% alpha level

# Prof. way to remove study and compare 
leave1out(FEM)

```

\newpage

```{r}

# MY PROGRAMMING EXERCISES
# (2a) Inverse-variance weighted meta-analysis on the log odds ratio (FEM)
## Build function that returns a vector with the log odds
log_odds_ratio = function(v) {
  num <- v[1]*(v[4]-v[3])
  den <- v[3]*(v[2]-v[1])
  or <- (num)/(den)
  log_or <- log(or)
}
## Apply to all dataset
df1_log_or <- apply(df1[,2:5], 1, log_odds_ratio)

## Create new column in dataframe with log-odds-ratio
df1$log_or <- df1_log_or
df1


```
